# Generated by Django 4.2.5 on 2023-10-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='has_used_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
