# Generated by Django 4.2.5 on 2023-10-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0002_userdetails_has_used_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_first_order',
            field=models.BooleanField(default=False),
        ),
    ]
