# Generated by Django 4.2.5 on 2023-10-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_package_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set(),
        ),
    ]
