# Generated by Django 4.2.5 on 2023-10-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_coupon_discount_remove_coupon_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
